{{- $dh := .Values.rag.devHost -}}
{{- if and $dh $dh.enabled (hasKey $dh "ssh") (not $dh.ssh.fromClaims) }}
apiVersion: v1
kind: Secret
metadata:
  name: devhost-ssh
type: Opaque
stringData:
  authorized_keys: |-
{{- $ak := (tpl ($dh.ssh.authorizedKeys | default "") $) -}}
{{- range $line := splitList "\n" $ak -}}
    {{ $line }}
{{- end }}
{{- end }}
