{{- $dh := .Values.rag.devHost -}}
{{- if and $dh $dh.enabled (hasKey $dh "ssh") (not $dh.ssh.fromClaims) -}}
apiVersion: v1
kind: Secret
metadata:
  name: devhost-ssh
type: Opaque
stringData:
  authorized_keys: |-
{{- $ak := tpl (default "" $dh.ssh.authorizedKeys) . -}}
{{- if $ak }}
{{ $ak | nindent 4 }}
{{- else }}
    # empty (no keys provided)
{{- end }}
{{- end -}}
