{{- $dh := .Values.rag.devHost -}}
{{- if and $dh $dh.enabled (hasKey $dh "ssh") (not $dh.ssh.fromClaims) ($dh.ssh.authorizedKeys) }}
apiVersion: v1
kind: Secret
metadata:
  name: devhost-ssh
type: Opaque
stringData:
  authorized_keys: |-
{{- range $line := splitList "\n" (tpl $dh.ssh.authorizedKeys $) -}}
{{- if $line }}
    {{ $line }}
{{- end }}
{{- end }}
{{- end }}

