llmosaic-db:
  org: example
  pgadmin:
    enabled: true

rag:
  examples:
    enabled: true
    source: image
    image: 148.153.46.195:30500/rag-examples:film-v8
  llmapi:
    baseUrl: https://llmapi6.llmosaic.ai

jupyterlab:
  enabled: true
  preload:
    enabled: true
    source: image
    image: 148.153.46.195:30500/rag-examples:film-v8
