llmosaic-db:
  org: example
  pgadmin:
    enabled: true

rag:
  examples:
    enabled: true
    source: dvc
    dvc:
      files:
        - repo_url: https://github.com/llmosaicai/llmosaic-rag
          repo_ref: main
          path: assets/film_db_backup.sql
          to: /artifacts/film_db_backup.sql
  llmapi:
    baseUrl: https://llmapi6.llmosaic.ai

jupyterlab:
  enabled: true
  preload:
    enabled: false
    source: inline
