apiVersion: v2
name: llmosaic-rag
description: RAG umbrella chart layered on llmosaic-db, with llmapi integration
type: application
version: 0.1.1
appVersion: "0.1.1"
dependencies:
  - name: llmosaic-db
    version: 0.1.1
    repository: "file://../../llmosaic-db/chart/llmosaic-db"
